# Apply only when running on OpenShift to let the kublet plugin run privileged
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints" -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dra-example-driver.fullname" . }}-openshift-privileged-role-binding
  namespace: {{ include "dra-example-driver.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dra-example-driver.serviceAccountName" . }}
  namespace: {{ include "dra-example-driver.namespace" . }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
{{- end }}
